'use strict';

const Path = require('path');
const Crypto = require('crypto');
const gen = require('easy-generator');
const Promise = require('bluebird');
const _exec = require("child_process").exec;

const TEMPLATES_DIR = Path.join(__dirname, '../templates');

const DATA_DEFAULTS = {
    // required
    mongoURI: undefined,

    // optional
    name: 'Site',
    description: '',
    version: '1.0.0',
    author: '',
    nodeVersion: '7.8',
    emcaVersion: '2017',

    BCRYPT_PASSWORD_SALT_ROUNDS: 10,

    // autogenerated
    JWT_SECRET: undefined,
};

function genJWTSecret () {
    return Crypto.randomBytes(256).toString('base64');
}

function create ({
    outputDir,
    data,
    template,
}) {
    const mergedData = Object.assign({}, DATA_DEFAULTS, { JWT_SECRET: genJWTSecret() }, data);
    return gen({ data: mergedData, templateDir: Path.join(TEMPLATES_DIR, template), outputDir });
}

module.exports = create;
