'use strict';

const Path = require('path');
const Crypto = require('crypto');
const gen = require('easy-generator');

const TEMPLATE_DIR = Path.join(__dirname, '../template');

const DATA_DEFAULTS = {
    // required
    mongoURI: undefined,

    // optional
    name: 'Site',
    description: '',
    version: '1.0.0',
    author: '',
    nodeVersion: '7.7',
    emcaVersion: '2017',

    BCRYPT_PASSWORD_SALT_ROUNDS: 10,

    // autogenerated
    JWT_SECRET: undefined,
};

function genJWTSecret () {
    return Crypto.randomBytes(256).toString('base64');
}

function create ({
    outputDir,
    data,
}) {
    const mergedData = Object.assign({}, DATA_DEFAULTS, { JWT_SECRET: genJWTSecret() }, data);
    return gen({ data: mergedData, templateDir: TEMPLATE_DIR, outputDir });
}

module.exports = create;
